backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: public/images
public_folder: /images
site_url: "https://resonant-bublanina-6e1de9.netlify.app/"

collections:
  - name: produit
    label: produits
    folder: src/content/produits
    create: true
    format: frontmatter
    preview_path: produit/{{slug}}
    fields:
      - { name: title, label: Title }
